@baseURL = http://localhost:8080

###############################################
# 1.0 Shorten a URL — happy path
###############################################

POST {{baseURL}}/shortner
Content-Type: application/json

{
    "url": "https://google.com"
}

###############################################
# 1.1 Shorten a URL — happy path
###############################################

POST {{baseURL}}/shortner
Content-Type: application/json

{
    "url": "https://pandaaritra.me"
}

###############################################
# 1.2 Shorten a URL — happy path
###############################################

POST {{baseURL}}/shortner
Content-Type: application/json

{
    "url": "https://youtube.com"
}

###############################################
# 2. Shorten — empty url
###############################################

POST {{baseURL}}/shortner
Content-Type: application/json

{
    "url": ""
}

###############################################
# 3. Shorten — malformed JSON
###############################################

POST {{baseURL}}/shortner
Content-Type: application/json

{ not valid json }

###############################################
# 4.0 Redirect — replace YOUR_CODE with code
#    from response of request 1
###############################################

GET {{baseURL}}/yXscKI


###############################################
# 4.1 Redirect — replace YOUR_CODE with code
#    from response of request 1
###############################################

GET {{baseURL}}/RGFTXQ


###############################################
# 4.2 Redirect — replace YOUR_CODE with code
#    from response of request 1
###############################################

GET {{baseURL}}/LfXZVb


###############################################
# 4.3 Redirect — replace YOUR_CODE with code
#    from response of request 1
###############################################

GET {{baseURL}}/yXscKI

###############################################
# 5. Redirect — code that doesnt exist
###############################################

GET {{baseURL}}/thisdoesnotexist

